name: DavidPuglia
favicon: null
layout_spectrum: 0.7285687092225999
typography_spectrum: 0.0968286506831646
title: Astrophotography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.811253777006641
  lightness: 0.8421307867392898
  saturation: 0.5982769001275301
  rhythmicContrast: 0.9785135732963681
purpose: []
